name: CI/CD for Docker Image

on:
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t ${{ github.repository }}:latest -t ${{ github.repository }}:${{ github.event.release.tag_name }} --push .
        env:
          DOCKER_CLI: docker

      - name: Push Docker Image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ github.repository }}:latest
          docker push ${{ github.repository }}:${{ github.event.release.tag_name }}
        env:
          DOCKER_CLI: docker

